package net.jfaker.model;

import java.util.Objects;

/**
 * Class to represent a superClass of all bots
 */
public class BotSuperClassInfo extends ClassInfo {

    private final ClassInfo generatedClass;

    /**
     * Constructor received a bot super class and class generated by bot who will implement it
     * @param qualifiedName qualifiedName of bot super class
     * @param generatedClass class generated by bot
     */
    public BotSuperClassInfo(final String qualifiedName, final ClassInfo generatedClass) {
        super(qualifiedName);
        this.generatedClass = generatedClass;
    }

    public ClassInfo getGeneratedClass() {
        return generatedClass;
    }

}
