package net.jfaker.model;

import java.util.Objects;

/**
 * Class to represent a superClass of all bots
 */
public class BotSuperClassInfo extends ClassInfo {

    private final ClassInfo generatedClass;

    /**
     * Constructor received a bot super class and class generated by bot who will implement it
     * @param qualifiedName qualifiedName of bot super class
     * @param generatedClass class generated by bot
     */
    public BotSuperClassInfo(final String qualifiedName, final ClassInfo generatedClass) {
        super(qualifiedName);
        this.generatedClass = generatedClass;
    }

    public ClassInfo getGeneratedClass() {
        return generatedClass;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof BotSuperClassInfo that)) return false;
        if (!super.equals(o)) return false;
        return Objects.equals(generatedClass, that.generatedClass);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), generatedClass);
    }

    @Override
    public String toString() {
        return "BotSuperClassInfo{" +
                super.toString() +
                ", generatedClass=" + generatedClass +
                '}';
    }
}
