package net.jfaker.annotation;

/**
 * configuration for create instance inside of bot using constructor strategy.
 * <pre>{@code
 *     public User build(){
 *         return new User(name.get(), email.get());
 *     }
 * }</pre>
 */
public @interface ConstructorStrategy {

    /**
     * specify here in order an arg qualified name type from constructor
     */
    String[] argsNames() default  {};

    /**
     * NO USE THIS CONFIG ! He is used for ignore all configs defined in this annotation.
     */
    boolean ignoreConfig() default false;

    /**
     * Array of String with fields generated by default null value when instance is generated
     */
    String[] fieldsInitNull() default "";

    /**
     * If you need some specific field using another provider or bot instance do set in a prop you can use this configuration
     */
    FieldConfiguration[] fieldsConfiguration() default {};

}
