package net.jfaker.annotation;

/**
 * configuration for create instance inside of bot using setter strategy.
 * <pre>{@code
 *     public User build(){
 *         var user = new User();
 *         user.setName(name.get());
 *         user.setEmail(email.get());
 *         return user
 *     }
 * }</pre>
 */
public @interface SetterStrategy {

    /**
     * If you need some specific field using another provider or bot instance do set in a prop you can use this configuration
     */
    FieldConfiguration[] fieldsConfiguration() default {};

    /**
     * Array of String with fields generated by default null value when instance is generated
     */
    String[] fieldsInitNull() default "";

    /**
     * Array of String with setters will be ignored in Bot creation
     */
    String[] settersToIgnore() default "";

    /**
     * NO USE THIS CONFIG ! He is used for ignore all configs defined in this annotation.
     */
    boolean ignoreConfig() default false;
}
